### ISSUE TITLE
can't open the script

### ISSUE THREAD

**Issue by ALXNDR02** [0xSpoofed/Vingod#7]
when i digit the command python Vingod.py the terminal says this error:
Traceback (most recent call last):
  File "C:\Users\alxndr\Vingod\vingod-src\Vingod.py", line 600, in <module>
    main(banner, c, w)
  File "C:\Users\alxndr\Vingod\vingod-src\Vingod.py", line 560, in main
    {c}[{w}1{c}]{w} Start              |    {c}[{w}>{c}]{w} Brand: {brand_converter(get_settings()[0])} ; {c}[{w}>{c}]{w} Decrease margin (%): {str(get_settings()[3]) + "%"}
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alxndr\Vingod\vingod-src\Vingod.py", line 101, in brand_converter
    json_data = read_json(f"{getcwd()}\\assets\\brands.json")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alxndr\Vingod\vingod-src\Vingod.py", line 70, in read_json
    data = load(json_file)
           ^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
                 ^^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbd in position 2088: illegal multibyte sequence

**Comment by 0xSpoofed** [comment]
Hello, 
Thank you for your feedback, unfortunately the bot has not yet been updated and is therefore not functional at the moment.
For any further information, please send a message here. 
Have a nice day
